### ISSUE TITLE
AWX rpm roadmap

### ISSUE THREAD

**Issue by tjyang** [MrMEEE/awx-build#12] opened 2018-04-10 21:36 UTC
Hi @MrMEEE 

What is the future roadmap for this awx-build project ? 

I have  a few  concerns.

1. awx-rpm is not available in EPEL repo.
2. There are only two persons working on awx rpm project.
3. AWX team is not willing to support  rpm install aproach.

What is your thought ?

**Comment by MrMEEE** [comment] 2018-04-10 22:23
Hi

On the short run.. I will just keep building rpms and fixing bugs as good as I can..

I have already tried to push the package into epel, but there is one major issue.. 

Right now the awx installation just grab a LOT of python dependencies during the build, and this is not supported by EPEL, as they do not allow builds that pulls stuff from the internet.. 

So in short, the build of awx into EPEL, will require me to sort out every single python dependency,  figure out which are already in EPEL, and which are in the wrong versions.. And then push all these packages to EPEL.. and then I can start building awx .. 

This will be a very long process (as I see it).. and it doesn't seem like I will receive any support from the AWX team.. 

Maybe over time we can gather some people, and do it together?

**Comment by tjyang** [comment] 2018-04-11 02:43
@MrMEEE 
I will spent time on  awx rpm effort and submit PR if I have things to contribute.

**Comment by sglepage** [comment] 2018-07-18 02:03
@MrMEEE Just confirming that

https://github.com/ansible/awx/blob/732698440f5278f085d28dd3870fad24b92d7736/requirements/requirements.in

and 

https://github.com/ansible/awx/blob/732698440f5278f085d28dd3870fad24b92d7736/requirements/requirements_ansible.in

Are the python dependencies you were referring to?

**Comment by MrMEEE** [comment] 2018-07-18 09:12
I'm actually using:

cat requirements/requirements_ansible.txt requirements/requirements_ansible_git.txt | \
    _buildenv/bin/pip install --no-binary cffi,pycparser,psycopg2,twilio --prefix=`pwd`/embedded/ -r /dev/stdin
cat requirements/requirements.txt requirements/requirements_git.txt | \
_buildenv/bin/pip install --no-binary cffi,pycparser,psycopg2,twilio --prefix=`pwd`/embedded/ -r /dev/stdin

In building of the RPM

**Comment by MrMEEE** [comment] 2019-01-28 12:28
@tjyang @sglepage 
Now that the new version of awx (now called ansible-awx) has been released, I have splitted all the requirements into separate rpms.. (took a while)..

The dependencies as well as ansible-awx specs are available here... https://github.com/MrMEEE/ansible-awx-depends

**Comment by tjyang** [comment] 2019-01-28 13:04
@MrMEEE , what is your OS version  ?  I like to try to build the spec files.

**Comment by MrMEEE** [comment] 2019-01-28 13:06
Fully updated CentOS7..

This script is what I use to install deps:
```
#!/bin/bash

ln -s /opt/rh/rh-python36/root/usr/bin/python3 /usr/bin/python3.6

yum -y install centos-release-scl

yum clean all

yum -y install python3-rpm-macros python-rpm-macros rh-python36-build rh-python36-python rh-python36-python-devel gcc make libffi-devel openssl-devel libxml2-devel libxslt-devel gcc-c++ rh-postgresql10-postgresql-devel openldap-devel xmlsec1-devel libxml2-devel xmlsec1-openssl-devel libtool-ltdl-devel rh-python36-python-sphinx rh-python36-python-six

yum -y install https://cbs.centos.org/kojifiles/packages/scl-utils-build-helpers/0/7.el7/noarch/scl-utils-build-helpers-0-7.el7.noarch.rpm

ln -s /opt/rh/rh-python36/root/usr/bin/sphinx-build /opt/rh/rh-python36/root/usr/bin/sphinx-build-3

ln -s /opt/rh/rh-postgresql10/root/usr/bin/pg_config /usr/bin/pg_config

ln -s /usr/include/libxml2/libxml /usr/include/libxml

export LC_CTYPE=en_US.UTF-8
```

**Comment by MrMEEE** [comment] 2019-02-07 01:40
@tjyang I have commited one of the packages for being accepted into the fedora build community.. But it's going to be quite at big project:

https://bugzilla.redhat.com/show_bug.cgi?id=1672659

**Comment by avylove** [comment] 2019-05-14 22:58
I would get rid of the rh-python36 SCL. EPEL 7 moved to Python 3.6, so most of what you need should be available or will be easier to add doing it as non-scl packages.

Some packages already exist in EPEL for Python 2, boto for example. You can try to get commit access to the repos or send a pull request with changes to update the versions and build for Python 3.6. Some maintainers are less responsive and you end up having to go through the [unresponsive maintainer procedures](https://fedoraproject.org/wiki/Policy_for_nonresponsive_package_maintainers).

Also wondering if azure packages and similar really need to be installed by default. Will AWX complain? If so I think that should be considered a bug.

**Comment by MrMEEE** [comment] 2019-05-14 23:08
@avylove I see your point.. but to have an environment that is as similiar to the docker version as possible, I prefer to build all of the packages myself, so I'm sure that I use exactly the same versions as in the upstream docker version..

I have earlier had issues that where caused by python packages not matching :(.. and as long as the AWX community doesn't wanna help develop the RPM version, I think that's the easiest way.. 

But it's good input, and if the AWX-RPM community grows I might do something like that one day.. 

Also, the application streams in RHEL8/CentOS8 will be quite interesting..

**Comment by Harshal-20** [comment] 2019-06-01 07:49
I really like what @MrMEEE and you guys are doing.  I am not a developer but has been using AWX and would like to learn and contribute on your efforts.  Please let me know how can I help.

**Comment by nkadel** [comment] 2019-06-05 13:48
@MrMEEE i would not burn cycles submitting SCL python package changes. Since EPEL now publishes the "python36" packages for RHEL and CentOS 7, I'd definitely switch to using those as better supported modules.

**Comment by MrMEEE** [comment] 2019-06-05 14:12
@nkadel  There is only 64 packages in the SCL Repository.. 

Right now AWX has around 280 dependencies: https://copr.fedorainfracloud.org/coprs/mrmeee/ansible-awx/packages/

I'm only building the ones that are not in the SCL repo, or is older..

**Comment by EdHunter87** [comment] 2019-10-17 14:14
Are there plans to add HTTPS configuration into the NGINX configuration?

**Comment by nkadel** [comment] 2019-10-18 01:03
Most of this has changed with the release of python3 for RHEL 7.7. No need for the SCL repos, though caution is needed for RHEL bs, EPEL dependencies. Simply using “BuildRequires: EPEL-rpm-macros” and correctly using “python3_pkgversion” should handle most of it.

**Comment by MrMEEE** [comment] 2019-10-18 07:25
@nkadel what do you mean when saying that the SCL repos are not needed?

**Comment by nkadel** [comment] 2019-10-18 08:47
I mean that the dedicated compilation of awx and python modules for it should be shiftable to the main python3_libdir and python3_archdir workspaces. It would requie cautious integration: the SCL workspace has provided isolation from system necessary python3 components that might overlap or conflict with your work. But in therms of basic python 3 support, you and others could, in theory, switch to using the base OS provided python 3.6. Switching would be very awkward and require *a lot* of revision.

**Comment by MrMEEE** [comment] 2019-10-18 08:49
Ok.. now I understand, and that's why I will probably wait for CentOS8.1 and do the migration to Streams/Modules there..

**Comment by MrMEEE** [comment] 2019-10-18 10:46
@EdHunter87 This is pretty easy, just normal nginx ssl config.. but yes, it should be done automatically.. I will create a separate issue for this

**Comment by nkadel** [comment] 2021-09-24 01:21
I think you can close this, or fork it do a distinct "refine this enough for EPEL ticket".

The modules in CentOS 8 will *not* help this: they're not compatible with CentOS 7, which is going to be very long-lived due to the unwelcome CentOS 8 Stream packaging, so it will be safer to just avoid it.

**Closed as completed** 2022-01-17 10:08 UTC
Labels: question
