### ISSUE TITLE
No virtualenv support

### ISSUE THREAD

**Issue by angystardust** [MrMEEE/awx-build#48] opened 2018-10-18 18:17 UTC
Hi @MrMEEE,
first of all thanks for your effort.
I've noticed that installing your last rpm (2.0.1) it doesn't allow to create custom venv and associate them to an organization. This feature was introduced in tower 3.0 and in 3.3 it was further streamlined:
https://docs.ansible.com/ansible-tower/latest/html/upgrade-migration-guide/virtualenv.html

On a setup using your rpm, I cannot see the "Ansible environment" option at all:
![screenshot from 2018-10-18 20-16-13](https://user-images.githubusercontent.com/1568397/47175147-b8e9c400-d312-11e8-8833-fe29655f4ac5.png)

Is it possible to enable this feature in your rpm?

**Comment by MrMEEE** [comment] 2018-10-19 08:50
Hi

I think it's related to https://github.com/ansible/awx/issues/1815...

I'll see what I can do...

**Comment by efenex** [comment] 2018-10-19 12:41
just had this same issue, restarting memcached and logging out/into AWX made the dropdown appear.

**Comment by MrMEEE** [comment] 2018-10-19 12:43
hmmmm... Not working here :(

**Comment by efenex** [comment] 2018-10-19 13:05
We are using your 2.0.1 RPM FYI. 

I wrote the following ansible code to create and configure the virtualenv's (maybe it can help you in case the issue is in the configuration):

```
---
- name: AWX | post_install | Install virtualenv package
  package:
    name: "{{ item }}"
  loop:
    - python-virtualenv
    - gcc
 
- name: AWX | post_install | Create virtualenvs
  pip:
    name:
      - pip
      - setuptools
    virtualenv: "/var/lib/awx/venv/ansible-{{ item }}"
  loop: "{{ awx.ansible_versions }}"

- name: AWX | post_install | Install awx dependencies into venv
  pip:
    name:
      - python-memcached
      - psutil
    virtualenv: "/var/lib/awx/venv/ansible-{{ item }}"
  loop: "{{ awx.ansible_versions }}"
 
- name: AWX | post_install | Install ansible inside venv
  pip:
    name: ansible
    version: "{{ item }}"
    virtualenv: "/var/lib/awx/venv/ansible-{{ item }}"
  loop: "{{ awx.ansible_versions }}"
 
#- name: AWX | post_install | Get API token if awx application details are provided
#  uri:
#    url: "http://{{ ansible_fqdn }}/api/o/token/"
#    method: POST
#    body: "grant_type=password&username={{ awx.admin_username }}&password={{ awx.admin_password }}&scope=write"
#    user: "{{ awx.api.username }}"
#    password: "{{ awx.api.password }}"
#    return_content: yes
#  register: token
#  when: "'username' in awx.api and 'password' in awx.api"
 
- name: AWX | post_install | Get API token if awx application details are provided
  command: curl -q -X POST -d "grant_type=password&username={{ awx.admin_username }}&password={{ awx.admin_password }}&scope=write" -u "{{ awx.api.username }}:{{ awx.api.password }}" "http://{{ ansible_fqdn }}/api/o/token/"
  register: token
  run_once: true
  when: "'username' in awx.api and 'password' in awx.api"

- set_fact:
    token: "{{ token.stdout | from_json }}"
 
- name: AWX | post_install | Configure custom venv for orgs when specified
  command: 'curl --request PATCH --data "{\"custom_virtualenv\": \"/var/lib/awx/venv/ansible-{{ item[1] }}/\"}" -H "Content-Type: application/json" -H "Authorization: Bearer {{ token.access_token }}" "http://{{ ansible_fqdn }}/api/v2/organizations/{{ item[0] }}/"'
  run_once: true
  when: "'access_token' in token"
  loop: "{{ awx.ansible_venv_org_mapping }}"

- name: AWX | post_install | Configure custom venv for projects when specified
  command: 'curl --request PATCH --data "{\"custom_virtualenv\": \"/var/lib/awx/venv/ansible-{{ item[1] }}/\"}" -H "Content-Type: application/json" -H "Authorization: Bearer {{ token.access_token }}" "http://{{ ansible_fqdn }}/api/v2/projects/{{ item[0] }}/"'
  run_once: true
  when: "'access_token' in token"
  loop: "{{ awx.ansible_venv_project_mapping }}"

- name: AWX | post_install | Configure custom venv for job templates when specified
  command: 'curl --request PATCH --data "{\"custom_virtualenv\": \"/var/lib/awx/venv/ansible-{{ item[1] }}/\"}" -H "Content-Type: application/json" -H "Authorization: Bearer {{ token.access_token }}" "http://{{ ansible_fqdn }}/api/v2/job_templates/{{ item[0] }}/"'
  run_once: true
  when: "'access_token' in token"
  loop: "{{ awx.ansible_venv_jobtemplate_mapping }}"
```

**Comment by MrMEEE** [comment] 2018-10-19 13:11
When I add a second venv, the dropdown shows up... hmmm... weird

**Comment by angystardust** [comment] 2018-10-19 13:15
by the way, i think we should replicate the same awx folder structure as the one in a tower setup:
```
/var/lib/awx/
|-- job_status
|-- projects
|-- public
|   `-- static
`-- venv
    |-- ansible
    |   |-- bin
    |   |-- include
    |   |-- lib
    |   `-- lib64 -> lib
    `-- awx
        |-- bin
        |-- include
        |-- lib
        `-- lib64 -> lib
```

**Comment by angystardust** [comment] 2018-10-19 13:20
@MrMEEE i think that the reason why the drop-down menu doesn't appear by default using your rpm is explained in this comment https://github.com/ansible/awx/issues/1815#issuecomment-385087991

**Comment by MrMEEE** [comment] 2018-11-07 10:04
@angystardust Can we close this?

**Comment by angystardust** [comment] 2018-11-07 10:13
@MrMEEE Yes, but please consider what i wrote in https://github.com/MrMEEE/awx-build/issues/48#issuecomment-431359396

**Comment by MrMEEE** [comment] 2018-11-07 10:15
@angystardust What is it that you see is different?

**Comment by MrMEEE** [comment] 2018-11-09 13:48
@angystardust ?????

**Comment by angystardust** [comment] 2018-11-09 18:37
sorry for the delay. What I mean is: on a Tower setup the awx and ansible binaries are inside a default venv while on your rpm the binaries are inside /opt/awx/bin

**Comment by Aglidic** [comment] 2018-11-09 20:44
the fact is you can recreate the venv like tower and it will work.

I already done that because i needed some specific module.

You need to recreate an ansible venv and reinstall ansible in that venv through pip
An create a second venv awx

Both venv should be in /var/lib/awx/venv

And after that you can add all python module needed

**Closed as completed** 2018-12-12 00:52 UTC
Labels: bug
