### ISSUE TITLE
failed to create symbolic link ‘/var/lib/awx/venv/awx’: No such file or directory

### ISSUE THREAD

**Issue by tjyang** [MrMEEE/awx-build#111] opened 2019-05-28 13:19 UTC
Hi @MrMEEE 

Following is an error message when upgrading from 558 to 616 
```
No Presto metadata available for mrmeee-ansible-awx
ansible-awx-4.0.0.616-1.el7.x86_64.rpm                     |  13 MB   00:05
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
usermod: no changes
  Updating   : ansible-awx-4.0.0.616-1.el7.x86_64                           1/2
ln: failed to create symbolic link ‘/var/lib/awx/venv/awx’: No such file or directory
warning: %post(ansible-awx-4.0.0.616-1.el7.x86_64) scriptlet failed, exit status                           1
Non-fatal POSTIN scriptlet failure in rpm package ansible-awx-4.0.0.616-1.el7.x8                          6_64
  Cleanup    : ansible-awx-4.0.0.558-1.el7.x86_64                           2/2
  Verifying  : ansible-awx-4.0.0.616-1.el7.x86_64                           1/2
  Verifying  : ansible-awx-4.0.0.558-1.el7.x86_64                           2/2

Updated:
  ansible-awx.x86_64 0:4.0.0.616-1.el7

Complete!
[root@awx01 ~]#

```

**Comment by tjyang** [comment] 2019-06-03 13:03
* ansible-awx.x86_64 0:4.0.0.650-1.el7 also has this issue.
```
[me@awx01 ~]$ sudo yum update ansible-awx -y
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.steadfastnet.com
 * centos-sclo-rh: mirror.steadfastnet.com
 * centos-sclo-sclo: mirror.steadfastnet.com
 * epel: mirror.us.leaseweb.net
 * extras: mirror.steadfastnet.com
 * updates: mirror.steadfastnet.com
Resolving Dependencies
--> Running transaction check
---> Package ansible-awx.x86_64 0:4.0.0.616-1.el7 will be updated
---> Package ansible-awx.x86_64 0:4.0.0.650-1.el7 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

=======================================================================================================================================
 Package                       Arch                     Version                             Repository                            Size
=======================================================================================================================================
Updating:
 ansible-awx                   x86_64                   4.0.0.650-1.el7                     mrmeee-ansible-awx                    13 M

Transaction Summary
=======================================================================================================================================
Upgrade  1 Package

Total download size: 13 M
Downloading packages:
No Presto metadata available for mrmeee-ansible-awx
ansible-awx-4.0.0.650-1.el7.x86_64.rpm                                                                          |  13 MB  00:00:01
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
usermod: no changes
  Updating   : ansible-awx-4.0.0.650-1.el7.x86_64                                                                                  1/2
ln: failed to create symbolic link ‘/var/lib/awx/venv/awx’: No such file or directory
warning: %post(ansible-awx-4.0.0.650-1.el7.x86_64) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package ansible-awx-4.0.0.650-1.el7.x86_64
  Cleanup    : ansible-awx-4.0.0.616-1.el7.x86_64                                                                                  2/2
  Verifying  : ansible-awx-4.0.0.650-1.el7.x86_64                                                                                  1/2
  Verifying  : ansible-awx-4.0.0.616-1.el7.x86_64                                                                                  2/2

Updated:
  ansible-awx.x86_64 0:4.0.0.650-1.el7

Complete!
[me@awx01 ~]$

```

**Comment by MrMEEE** [comment] 2019-06-03 13:07
Thanks for reporting..

This should be fixed from the next version :)

**Comment by tjyang** [comment] 2019-06-03 13:19
Thanks for the creating this ansible-awx rpm.

* Another issue I ecountered.
```
following conflicted file causing  rh-pythion36-ipaddress update to fail. 
/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/__pycache__/ipaddress.cpython-36.opt-1.pyc

# fix: sudo yum remove rh-python36-ipaddress-1.0.19 so nwer version can be installed.

```

**Comment by MrMEEE** [comment] 2019-06-04 06:17
Hi again..

There are now a couple of new versions available, can you confirm that the issue is fixed?

in regards to the dependency issue, then I'm aware that there are a few issues, after I changed the naming convention.. I have now completely removed rh-python36-python-ipaddress .. thanks for noticing

**Comment by tjyang** [comment] 2019-06-04 10:56
>There are now a couple of new versions available, can you confirm that the issue is fixed?
Yes. I was able to have smooth upgrade from 4.0.0.650 to  4.0.0.661. Thanks for the fix.

**Comment by MrMEEE** [comment] 2019-06-04 12:44
Cool.. thanks for the feedback

**Closed as completed by MrMEEE** 2019-06-04 12:44 UTC
Labels: bug - nonreproducable
